/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Soccer-ball.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Soccer-ball.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.soccer_ball2.geometry} material={nodes.soccer_ball2.material} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Soccer-ball.glb')
